### ISSUE TITLE
Neutral bone - unique ID error on MSFS sim build

### ISSUE THREAD

**Issue by erasam** [ronh991/glTF-Blender-IO-MSFS#25]
### Current Behavior

I have several armatures on my Blender model but one of them when building the project in MSFS gives me the error:

"Node without Unique ID while using the unique_id extension, nodes[296] : 'neutral_bone'"

I think it is because I have several neutral bones in the model

I'm using the following export settings:

<img width="404" height="838" alt="Image" src="https://github.com/user-attachments/assets/b918d605-70db-4be5-92ac-a8b68154eff8" />

How can I solve it ?

P.S: I'm using the 1.6.12.0 version of the exporter and Blender 3.6.23 LTS ()

### Expected Behavior

No error during build

### Steps To Reproduce

Just export the model

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

**Comment by ronh991** [comment]
Hmm, this should have been fixed. can you try the latest release?

**Comment by ronh991** [comment]
Oooops, sorry - I see I said that the latest release only works with 4.2 - It should also work with 3.6.

**Comment by erasam** [comment]
I have installed release 1.6.13.0 but I still face this error while building the project

Node without Unique ID while using the unique_id extension, nodes[298] : 'neutral_bone'

I checked in the gltf and I see just one neutral_bone there:
       {
			"name":"neutral_bone",
			"rotation":[
				-0.7071067690849304,
				0,
				0,
				0.7071067690849304
			]
		},
		{
			"extensions":{
				"ASOBO_unique_id":{
					"id":"HANDLING_RudderPedal_2_Rudder_Wire.001"
				}
			},
			"mesh":266,
			"name":"HANDLING_RudderPedal_2_Rudder_Wire.001",
			"skin":2
		},
		{
			"extensions":{
				"ASOBO_unique_id":{
					"id":"RudderPedal_1_Rudder_Wire_Bone"
				}
			},
			"name":"RudderPedal_1_Rudder_Wire_Bone",
			"rotation":[
				0.6423820853233337,
				-0.05100825056433678,
				0.06438955664634705,
				0.7619694471359253
			],
			"scale":[
				0.9999997615814209,
				0.9999999403953552,
				0.9999998807907104
			],
			"translation":[
				0,
				0.0010742396116256714,
				0.03699684143066406
			]
		},
		{
			"extensions":{
				"ASOBO_unique_id":{
					"id":"HANDLING_RudderPedal_1_Rudder_Wire_Armature_neutral_bone"
				}
			},
			"name":"HANDLING_RudderPedal_1_Rudder_Wire_Armature_neutral_bone",
			"rotation":[
				-0.7071067690849304,
				0,
				0,
				0.7071067690849304
			]
		},

**Comment by erasam** [comment]
Strange I had in the past the same issue but with release 1.6.12.0 it was solved...

**Comment by ronh991** [comment]
Ok it seems to be doing what I wanted in the code

the HANDLING_RudderPedal_1_Rudder_Wire_Armature_neutral_bone is a rename of neutral_bone - adding a prefix of the name of the mesh.  However I see a "neutral_bone" without a prefix. I assume you have an interior and exterior.  this "neutral_bone" may be in both. So the system sees two and causes an error.  I don't know why it does not rename it as it does the others.

can you send me the blender file?

**Comment by erasam** [comment]
[Bone Issue.zip](https://github.com/user-attachments/files/21390129/Bone.Issue.zip)

I have isolated here the items causing the issue

If you generate the gltf using the exporter in the Bones_INT_LOD00.gltf there is a neutral_bone without the extension to generate a unique ID

**Comment by ronh991** [comment]
looking at your file - A question - if you manually remove those TWO neutral bones does the model still work?  They only have a rotation applied to them

Just an FYI your scale is set to 0.023 not 1.0

**Comment by ronh991** [comment]
Ok I have added a random number generation to the neutral_bone name - this should help in the duplicate naming.

here is a update to exporter for Blender 3.6

The exporter here for Blender 4.2 does not seem to set a "neutral_bone" for your sample.
But Blender 3.6 LTS has reached it's life limit and will not be updated.

People should move to 4.2 if they have issues and yell at ASOBO if 4.2 does not work with the exporter.

**Comment by erasam** [comment]
The animations are still WIP (those two are to deform two cables) as I stopped when I found the issue

If I move the armatures to a collection not involved in the export it goes well but obviously the cables are not moving as they should

**Comment by erasam** [comment]
I have installed your latest version and now I have the same error but for a different node name:

**Node without Unique ID while using the unique_id extension, nodes[262] : 'neutral_bone33'
Node without Unique ID while using the unique_id extension, nodes[269] : 'neutral_bone70'
Node without Unique ID while using the unique_id extension, nodes[304] : 'neutral_bone18'**

You see here three errors as I tried to export the whole model where I have several armatures in it

It seems now it save the neutral_bone(s) with a different name but it's not applying yet the extension as in this case (correctly managed):
"extensions":{
"ASOBO_unique_id":{
"id":"HANDLING_RudderPedal_1_Rudder_Wire_Armature_neutral_bone"
}

**Comment by erasam** [comment]
If you try to export the **Bone Issue.blend** with the latest release you see the _neutral_bone(s)_ are now named as _neutral_bone73_ and _neutral_bone74_ but no ASOBO_unique_id extension is applyd to it

**Comment by ronh991** [comment]
ok thanks for testing. Unfortunately this is a blender/Khronos bug of adding a neutral bone - I reported a long time ago.  Blender 3.6 has reached its life end. so no more bug fixes. 

What happens if you uncheck unique ID?

I will try to see if I can get a unique id on this mystery mesh.

If you manually remove those nodes from the gltf does the model work?

**Comment by ronh991** [comment]
ok try this update - same version number

[io_scene_gltf2_msfs_for36.zip](https://github.com/user-attachments/files/21414309/io_scene_gltf2_msfs_for36.zip)

**Comment by erasam** [comment]
Meanwhile I tried to delete the neutral_bone entry from the gltf but then the fspackager.exe crashed

Instead unchecking the unique ID made the export and the build executed without errors but I haven't tried yet to see the result in the sim

I have now downloaded your latest version and I see in the gltf all the neutral_bone have the unique_id extension applied to them, but once I tried to build the project I had the error two nodes were using the same unique id "neutral_bone64"

But exporting and building again the project there was no more any error (I think the random sometimes can generate the same number used as suffix fo the neutral_bone)

**Comment by erasam** [comment]
I'm still checking the outcome of the exported project as it seems there is a strange behavior in the sim for some animated bones

I'll give you a feedback when tests are completed
